### ISSUE TITLE
.Gif Support (and other minor issues)

### ISSUE THREAD

**Issue by Rubberduckycooly** [megamarc/Tilengine#22]
1. Hello! I have been working on integrating this into my project and I noticed that all my .gif files I use as assets (spritesheets) don’t load, and upon further reading it seems that (non-animated) gif files aren’t supported, are there any plans to add support for them?

2. Also as a side note, I have developed my own animation engine for sprites that defines properties for each frame (clip rectangle, spritesheet, delay, etc.) but I am unsure how I can pass this data to the tilengine sprite class without having to write it to a text file. For example, is there a way for me to load the values from my animation file and pass them into the tilengine sprite class?

3. Not a huge issue right now, but is there anyway that I could pass data from my own map file format to tilengine without having to remake it in tiled?

Other than that tilengine works like a dream!

**Comment by megamarc** [comment]
Hello, I answer next to your questions:

> I have been working on integrating this into my project and I noticed that all my .gif files I use as assets (spritesheets) don’t load, and upon further reading it seems that (non-animated) gif files aren’t supported, are there any plans to add support for them?

Currently Tilengine only loads **8-bit png** and **8-bit bmp**. Source code for the loaders can be found here: https://github.com/megamarc/Tilengine/tree/master/src_lib

> I have developed my own animation engine for sprites that defines properties for each frame (clip rectangle, spritesheet, delay, etc.) but I am unsure how I can pass this data to the tilengine sprite class without having to write it to a text file. For example, is there a way for me to load the values from my animation file and pass them into the tilengine sprite class?

The problem is not the format in which the data is stored on file, but how the features on your animation engine correspond to features in Tilengine. The source code of the Spriteset loader is [LoadSpriteset.c](https://github.com/megamarc/Tilengine/blob/master/src_lib/LoadSpriteset.c) that at the end calls [TLN_CreateSpriteset()](http://www.tilengine.org/doc/_tilengine_8h.html#ae8b14339520adea93f6716fbc4eff645), passing a bitmap and an array of [TLN_SpriteData](http://www.tilengine.org/doc/struct_t_l_n___sprite_data.html) structs with the attributes of each sprite. That's what you can pass to tilengine to create a Spriteset.

> Not a huge issue right now, but is there anyway that I could pass data from my own map file format to tilengine without having to remake it in tiled?

Of course, you can directly call [TLN_CreateTilemap](http://www.tilengine.org/doc/_tilengine_8h.html#a2d8bdfdac1df000401dbd6e16d4324ea) and feed it with suitable data loaded from your own assets. The source code for the current loader is [LoadTilemap.c
](https://github.com/megamarc/Tilengine/blob/master/src_lib/LoadTilemap.c). Once again the real issue is the data on your tilemap format is compatible with tilengine features.

If I know the internal format of the data you're trying to load, I may help you writing a custom loader for your spritesets and tilemaps.

> Other than that tilengine works like a dream!

I'm glad you're enjoying it!
