### ISSUE TITLE
Attempting To Load A PNG-24 Results In A Crash, Rather Than An Error

### ISSUE THREAD

**Issue by bhelyer** [megamarc/Tilengine#24]
The fact that the formats supported does not include PNG-24 will catch a lot of people out I'd imagine. I think it should return an error indicating an invalid bitmap format, rather than a rather alarming crash as happens now. 

I also think that the error message returned by TLN_GetErrorString should mention PNG8 and BMP8 somewhere in there, as it will set new users on the right path sooner rather than later.

(Side note: the only way I've found that I can create reliable PNG8 files is using an old webexport plugin for the GIMP -- the PNG8 files produced by Photoshop CS2 (the version I have available) end up with weird black corruption when displayed by Tilengine)

**Comment by megamarc** [comment]
The loader discards other bit depths than 8 bpp. However there's a fault in the interpretation of bit depth returned by libpng, the loader thinks that it's a valid 8 bpp when it is in fact 24 or 32, and then crashes due to unexpected data size mismatch. Fixing it in next release.
I've used the old Photoshop 7 and Photoshop CS5 to save PNG8 without any issue. Don't use "Save for web and devices" UI. First convert it to 8 bpp with "Image / mode / Indexed color..." and then use plain "Save As..." and select PNG.
