### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by SamSmith01** [megamarc/Tilengine#29]
I know that this isnt really an issue, but I didn't know how to solve my problem in any other way.
I succesfully downloaded the binaries fro itch.io and I also have python and sdl2 installed, but when i try to import tilengine in python, I receive the error "no module named 'tilengine'". It's obvious to me that python does not find the module, but because I am relatively new to coding, I don't know what I did wrong. Do I have to put the files in any particular directory? I also think that a lot of relatively new coders could be stuck here as well and so the README could have a little more detailed instructions on this topic?

**Comment by megamarc** [comment]
Hi Sam,

I'm glad you're trying tilengine! What OS are you using? Windows or Linux?
For general support and help questions, I invite you to register to the official forums (it's free), so other users can benefit from all questions and answers posted there, instead of having support scattered across different forums:
http://www.tilengine.org/forum/index.php

I hope to solve your question there! Sure you have valuable suggestions and ideas.
