### ISSUE TITLE
Add Mouse Support

### ISSUE THREAD

**Issue by everyfan** [megamarc/Tilengine#37]
I have a project I'd like to do in this engine that would require mouse support. I'm not asking for something complicated; just letting me know when a mouse button has been clicked and which pixel position on the screen (I'd expect I'd be figuring out which tile or sprite had been clicked on myself). I don't know how hard that would be to implement.

**Comment by megamarc** [comment]
Hi @everyfan, assisted mouse support was introduced in release 1.21, exposing the underlying SDL2 events to tilengine with the [SDL_SetSDLCallback](http://www.tilengine.org/doc/_window_8c.html#aa08ccc9e8f1ac7e86ed9e18979f35ced) function. This API function is briefly documented but easy to use, and there's a fully working example in the main repository: https://github.com/megamarc/Tilengine/blob/master/samples/TestMouse.c.
You'll need the SDL2 development headers because the example interfaces directly with the SDL2 library.

**Comment by daltomi** [comment]
Hi Marc.

I have a problem with this, it has to do with the window factor.
In TestMouse.c 
```c
#define WIDTH 400  // I only take the width to simplify
```
Next, Window.c https://github.com/megamarc/Tilengine/blob/dd886131d62cddcac2069c1d9801d5ef5810567f/src/Window.c#L180
```c
wnd_width = 400 * 3;  then wnd_width equal to 1200
```
The SDL_Mouse coordinates correspond to the window(w=1200), not the sprite(x= 180 y=166)
The solution is simple, get the factor and then divide that factor to the mouse coordinate:

If Window.c
```c
 factor = 3
```
Then TestMouse.c
```
if (entity->enabled &&
 mouse->x / factor >= entity->x && mouse->y / factor  >= entity->y &&
```
Is it possible to change the API, to return the factor, or better, to transform a coordinate according to the factor?

**Comment by megamarc** [comment]
@daltomi: of course that's a bug! Thanks for pointing it. I'll fix it. Mouse input should return the coordinates in framebuffer space, not in window space. Window scaling factor shouldn't affect the returned value.
@everyfan: the SDL2 bridge to handle events is implemented into the main library, but not into the python binding.
