### ISSUE TITLE
Incompatibility with non indexed PNG

### ISSUE THREAD

**Issue by GithubPrankster** [megamarc/Tilengine#64]
I was recently trying out Tilengine for a possible game idea but found that if I saved sprites using the sprite tool Aseprite ([https://www.aseprite.org/](url)), things would not load! I believe this may be a fault from the used libpng which I suggest looking into. Aseprite is open source as well. 
([https://github.com/aseprite/aseprite/](url))
I suggest look into this soon as many sprite artists today have been using it.

I am sending too the image I saved with Aseprite. Maybe you could find what went on.

![beach](https://user-images.githubusercontent.com/33995085/77187376-20311800-6ab3-11ea-9793-64682e97fd3f.png)

**Comment by GithubPrankster** [comment]
I have figured out the main issue: In LoadBitmap.c, line 123, the code assumes the PNG will always be a 8bpp indexed one.

[https://github.com/megamarc/Tilengine/blob/master/src/LoadBitmap.c#L123](url)

Aseprite allows you thankfully to assign a Color Mode (RGB Color, Greyscale, Indexed) so I just had to turn on Indexed and it seemed very fine. However I suggest either inform to the user it is not indexed (maybe throw a warning!) or convert the image to indexed through some manner. I do not work with libpng so I don't know how i'd do that.

**Comment by megamarc** [comment]
Hi!
Tilengine requires images to be 8 bpp indexed, that's why the loader explicitly refuses non-indexed images. This is unrelated to libpng itself.
If you enable error logging with [TLN_SetLogLevel(TLN_LOG_ERRORS)](http://www.tilengine.org/doc/group__setup.html#gaef32f0c87b4616df4f6780d0fe014cac) -very recommended- you'll see a line on the standard output complaining about wrong format:

`Tilengine: Resource file has invalid format`

**Comment by megamarc** [comment]
Feature added in release 2.6.0. Image must have less than 255 unique colors.
