### ISSUE TITLE
OSX build

### ISSUE THREAD

**Issue by alemelis** [megamarc/Tilengine#70]
there are no binaries for OS X in itch.io (not the latest release at least)

so I imagine you have to build them from the repo code

however, there's no CMakeLists.txt in the repo...

can you give more information on how to build the `Tilengine.dylib`? thanks!

**Comment by megamarc** [comment]
Hi! Thanks for your contribution :-)
Tilengine doesn't build with CMake, only basic GNU make and gcc is required. Apple distributes it under "Command-line tools for Xcode". 
SDL2 framework must be installed too, get it here:
https://www.libsdl.org/release/SDL2-2.0.12.dmg

Once everything it's installed, just switch to /src subfolder and run:
`make`
It should build Tilengine.dylib now

**Comment by alemelis** [comment]
hey thanks for the quick reply!
it works fine with the Makefile :)

I had to change
https://github.com/megamarc/Tilengine/blob/6ee8ef5d7d6f142bb532ee564365f12ab78556a5/src/Makefile#L30

to

```
LIBS = -lpng -lz -F /Library/Frameworks/ -framework SDL2 -lc
```

this is probably due to me not refreshing some cache even though there's no mention of this in the SDL2 docs

thanks again!

**Comment by megamarc** [comment]
Hi again! I'm glad it works now :-)

I used to provide OSX builds in the past. As I don't own any apple device, I used a hacked version of VMWare Player 12 under Windows 10, with a virtual machine of OSX 10.11 inside (vanilla VMWare doesn't allow this due to licensing and legal issues). After a major upgrade of Windows, it stopped working, requesting me to install a new version of VMWare.

I don't have experience on OSX environment, just the minimum to make Tilengine build. If you think there's something wrong inside the Makefile -something that may have worked in the past but doesn't do anymore-, feel free to make a pull request with the fix and I'll apply it.

**Comment by megamarc** [comment]
Hi,
I've managed to build again for OSX, there are binaries on itch.io. Could you please check if this build runs in newer versions of the OS? My virtual machine runs OSX 10.11 "El Capitan" from 2015, and I don't know if it runs in newer versions too or there are compatibility problems.
Thanks!

**Comment by alemelis** [comment]
Hello!

just tried the build from itch.io, works fine on my Mac as well, thanks for checking it

did you have to change the Makefile or di d you simply used the one in the repo?

**Comment by megamarc** [comment]
Thanks for the feedback. I used the Makefile in the repo, worked as always
