### ISSUE TITLE
No Isometric support

### ISSUE THREAD

**Issue by GithubPrankster** [megamarc/Tilengine#75]
Good evening, I was testing out a new perspective for my game, so I had made a map in Tiled that utilized it.
![image](https://user-images.githubusercontent.com/33995085/90298996-bdc62300-de6a-11ea-9146-ed93b9fa1240.png)
However, when I got it onto Tilengine, it appeared the same as any old *Orthogonal* tilemap!
![image](https://user-images.githubusercontent.com/33995085/90299041-e2ba9600-de6a-11ea-9245-b951d67c321e.png)
I may try working in a different perspective (45º or similar) but I am sad that I could not try this out. There are games out there such as Super Mario RPG which utilize an isometric view and I was seeking to capture that. Perhaps support could be added? Granted, it may require work around the third dimension which could be a hassle, but I seek some opinions on this.

**Comment by megamarc** [comment]
Hi!
Classic 2D VDP chips don't have direct support in hardware for "diamond" isometric tiles, nor does Tilengine do. Only orthogonal mode is supported, following its working principles. Very few isometric games for the SNES or Megadrive/Genesis were created, because they are hard to implement. Developers must work with squared tiles split diagonally combining two "materials", one on each side.

This is the actual tileset of isometric game "Populous" (https://www.youtube.com/watch?v=Ynb5-F6TPic):
![Populous](https://user-images.githubusercontent.com/14149983/90306023-352a9f80-dec9-11ea-9218-46d26fc97e87.png)

If you load this png as a 8x8 orthogonal tileset in Tiled and examine it, you'll se what I mean. This is the way to go.

**Comment by GithubPrankster** [comment]
Ouch, I think it would be less painful for me to just go with a typical top down perspective. Implementing depth would be too tricky for me. Thanks for the opinion :0

**Comment by megamarc** [comment]
Another option could be to interleave 2 layers displaced by half of the tileset size: if your "diamond" tileset is 32x32, use 2 layers that are offset by 16x16:

- layer 0 starts at 0,0
- layer 1 starts at 16x16
- fill both layers with 32x32 "diamonds"

Now the "holes" in one layer should be filled by the other layer. However using this method you won't be able to use different layers to implement depth (front/back of sprites), but if your gameplay is going to be flat, it can do the trick.
