### ISSUE TITLE
Unable to run applications  (0xc000007b)

### ISSUE THREAD

**Issue by EzzypooOfNazareth** [megamarc/Tilengine#79]
I have tried both 32 and 64 bit builds, tried using visual studio and codeblocks, tried using g++ and windows compiler to build the project. However whenever I attempt to run the project I get the following error:

The application was unable to start correctly (0xc000007b). Click OK to close application.

I would appreciate any help as the project builds fine, this only happens when trying to run tilengine applications.

**Comment by megamarc** [comment]
Hi,This specific error happens when you mix 32 and 64 binaries. Make sure that Tilengine.dll, SDL2.dll and the end application are all either 32 or 64 bit versions.Let me know,El 12 mar. 2021 21:02, Ezra Moore ***@***.***> escribió:
I have tried both 32 and 64 bit builds, tried using visual studio and codeblocks, tried using g++ and windows compiler to build the project. However whenever I attempt to run the project I get the following error:
The application was unable to start correctly (0xc000007b). Click OK to close application.
I would appreciate any help as the project builds fine, this only happens when trying to run tilengine applications.

**Comment by EzzypooOfNazareth** [comment]
Thanks for the quick response, the problem ended up actually being from the linker in codeblocks, I set it to search for sdl in the lib folder without specifying the Win32 or 64 bit versions
