### ISSUE TITLE
Documentation page on website is not available

### ISSUE THREAD

**Issue by lightofanima** [megamarc/Tilengine#8]
I couldn't find a contact form/email, so I'm mentioning it here!

Basically the documentation page (http://www.tilengine.org/documentation.htm) is not available, resulting in 502 Bad Gateway :slightly_smiling_face:

**Comment by megamarc** [comment]
Thanks for your report. The email link is located at the bottom of the main page, next to the follow in facebook and youtube links. It's easy to skip it unnoticed, maybe I should emphasize it a bit. It's [info@tilengine.org](mailto:info@tilengine.org)

The "bad gateway error" you saw may be caused by some firewall/network issue, the address is correct as you can see in this screenshot taken a few minutes ago:
![issue_8](https://cloud.githubusercontent.com/assets/14149983/22669633/df58de08-ecc5-11e6-8cd2-b089c523722a.jpg)

**Comment by lightofanima** [comment]
Hey, thanks for the response! I see the email now . . . . It was just hidden behind a link, which made it difficult to see :)

And you seem to be right . . . . The api page works for me now. That was quite strange.

Thank you, and sorry to bother!

**Comment by megamarc** [comment]
No problem, thanks for your interest!
