### ISSUE TITLE
Pausing Specific Animations

### ISSUE THREAD

**Issue by danielgholmes** [megamarc/Tilengine#93]
I have a use case where I will need to pause animations for certain sprites while others run. For example, I have character avatars with talking animation that need to run while the rest of the gameplay animations are paused.

I'm trying something like the code below where the game loop doesn't update anything else if there is dialogue on the screen. The problem is that when I do this, the animations for the rest of the game sprites continue.

```python
while window.process()

    if dialogue.speaking():
       dialogue.update()
       continue

      # the rest of game loop code...
```

Tilengine basically carries on with the animations every time I update the frame and I have no control over it.

How can I pause animation for specific sprites? I had a look in [Animation.c](https://github.com/megamarc/Tilengine/blob/830205ebbc51b5e273c8c5d2f4dfd3b41b750c13/src/Animation.c) but I don't see functionality to pause animations.

**Comment by megamarc** [comment]
Hi,
Implementing `TLN_PauseAnimation(index)` and `TLN_ResumeAnimation(index)` should be easy, that's what you need.
However, in the meantime you can disable them with `TLN_DisableSpriteAnimation(index)` and re-enable them again with `TLN_SetSpriteAnimation(index, ...)`. This method has the drawback that the animation will restart from the beginning instead of continuing from the last frame.

Is this enough for now, or you need freezing at specifing point and continue from that point?

**Comment by megamarc** [comment]
I understand, this is a required feature. No problem 👌El 28 mar. 2022 17:44, Daniel Holmes ***@***.***> escribió:
Hi Marc,
Unfortunately there are some animations, for example the explosions, that need to paused and then resumed.
